### PR TITLE
Prepending module rewrite rules to .htaccess instead of appending

### PR DESCRIPTION
**Pull request by arouiadib**
When I directly visit the original image via browser addess bar (no http referrer), they unfortunately appear, which is not the aim of the module IMHO.

examples that work:

ip_address/4/6/46.jpg
ip_address/img/p/4/6/46.jpg

Moving the module htaccess rules to the top of the .htaccess makes the urls lead to 403 forbidden as intended.

Thank you.

### CODE REVIEW

**Review by rblaurin — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Not sure it's a good idea, if you prepend it and your server is not proplery configure for rewrite.
Rewrite rules will fall because `RewriteEngine` will be after. :thinking:

**Comment by arouiadib** [comment]
@PierreRambaud , here is a sample of the code generated by watermark module inside .htaccess:

```
# ~~end~~ Do not remove this comment, Prestashop will keep automatically the code outside this comment when .htaccess will be generated again
# start ~ module watermark section
<IfModule mod_rewrite.c>
Options +FollowSymLinks
RewriteEngine On
RewriteCond expr "! %{HTTP_REFERER} -strmatch '*://%{HTTP_HOST}*/admin453cuwx84/*'"
RewriteRule [0-9/]+/[0-9]+\.jpg$ - [F]
</IfModule>
# end ~ module watermark section
```

As you can see, it already contains `RewriteEngine` activation if  mod_rewrite exists. Appending it to htaccess doesn't allow protection of original images, when prepending does. Don't remember now why, because it is an old issue, but I think it works for a shop that started with 1.7.4.2 and now is 1.7.6.5.

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
> @PierreRambaud , here is a sample of the code generated by watermark module inside .htaccess:
> 
> ```
> # ~~end~~ Do not remove this comment, Prestashop will keep automatically the code outside this comment when .htaccess will be generated again
> # start ~ module watermark section
> <IfModule mod_rewrite.c>
> Options +FollowSymLinks
> RewriteEngine On
> RewriteCond expr "! %{HTTP_REFERER} -strmatch '*://%{HTTP_HOST}*/admin453cuwx84/*'"
> RewriteRule [0-9/]+/[0-9]+\.jpg$ - [F]
> </IfModule>
> # end ~ module watermark section
> ```
> 
> As you can see, it already contains `RewriteEngine` activation if mod_rewrite exists. Appending it to htaccess doesn't allow protection of original images, when prepending does. Don't remember now why, because it is an old issue, but I think it works for a shop that started with 1.7.4.2 and now is 1.7.6.5.

I approve the pull request, but after watching the code, this module needs a huge refactoring :sweat_smile:

**Comment by arouiadib** [comment]
Hi @PierreRambaud , I am really interested to know what are the changes that should be brought in this refacto. Could you please send me some guidelines (or a PR with similar goal). That would be appreciated .
Thanks for your time

**Comment by PierreRambaud** [comment]
@arouiadib You can have a look on ps_linklist or ps_facetedsearch modules.
Globally, constants must be added, methods must be split in classes, remove duplicate code, ... :sweat_smile:

**Comment by arouiadib** [comment]
@PierreRambaud , thank you very much I see now. I will work on it, interesting!

**Comment by PierreRambaud** [comment]
Thanks @arouiadib

**Pull request merged**
